In [1]:
import os
import json
import pandas as pd
import streamlit as st
import plotly.express as px
import mysql
import mysql.connector

In [3]:
path = r"E:\Guvi\Final Projects\Phonepe Pulse Data\data\aggregated\transaction\country\india\state"
data = os.listdir(path)
aggregate_transaction_data = []
q = 0

for i in data:
    path = fr"E:\Guvi\Final Projects\Phonepe Pulse Data\data\aggregated\transaction\country\india\state\{i}"
    data = os.listdir(path)
    for j in data:
        path = fr'E:\Guvi\Final Projects\Phonepe Pulse Data\data\aggregated\transaction\country\india\state\{i}\{j}'
        data = os.listdir(path)
        for k in data:
            path = fr'E:\Guvi\Final Projects\Phonepe Pulse Data\data\aggregated\transaction\country\india\state\{i}\{j}\{k}'
            q = q+1
            #print(q)
            file = open(path,'r')
            data = json.loads(file.read())
            #print(data)
            for t in range(len(data['data']['transactionData'])):
                transaction_data = {
                            'State' : i,
                            'Year' : j,
                            'Quarter' : q,
                            'Transaction_Name' : data['data']['transactionData'][t]['name'],
                            'Count' : data['data']['transactionData'][t]['paymentInstruments'][0]['count'],
                            'Amount' : int(float(data['data']['transactionData'][t]['paymentInstruments'][0]['amount']))
                            }
                aggregate_transaction_data.append(transaction_data)
        q = 0
df_aggregate_transaction = pd.DataFrame(aggregate_transaction_data)
df_aggregate_transaction.State = df_aggregate_transaction.State.str.title()
df_aggregate_transaction['State'] = df_aggregate_transaction['State'].str.replace(r'-', ' ', regex=True)
df_aggregate_transaction['State'] = df_aggregate_transaction['State'].str.replace(r'Islands', '', regex=True)
df_aggregate_transaction['State'] = df_aggregate_transaction['State'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu',regex=True)
aggregate_transaction_data = df_aggregate_transaction.T.to_dict().values()

In [7]:
path = r"E:\Guvi\Final Projects\Phonepe Pulse Data\data\aggregated\user\country\india\state"
data = os.listdir(path)
aggregate_user_data = []
q = 0

for i in data:
    path = fr"E:\Guvi\Final Projects\Phonepe Pulse Data\data\aggregated\user\country\india\state\{i}"
    data = os.listdir(path)
    for j in data:
        path = fr'E:\Guvi\Final Projects\Phonepe Pulse Data\data\aggregated\user\country\india\state\{i}\{j}'
        data = os.listdir(path)
        for k in data:
            path = fr'E:\Guvi\Final Projects\Phonepe Pulse Data\data\aggregated\user\country\india\state\{i}\{j}\{k}'
            q = q+1
            #print(k)
            file = open(path,'r')
            data = json.loads(file.read())
            #print(data)
            #print(len(data['data']['usersByDevice']))
            try:
                for t in range(len(data['data']['usersByDevice'])):
                    #print(t)
                    user_data = {
                                'State' : i,
                                'Year' : j,
                                'Quarter' : q,
                                'Registered-Users' : data['data']['aggregated']['registeredUsers'],
                                'Device-Brand' : data['data']['usersByDevice'][t]['brand'],
                                'Device-Count' : data['data']['usersByDevice'][t]['count'],
                                'Percentage-by-device' : data['data']['usersByDevice'][t]['percentage']
                                }
                    aggregate_user_data.append(user_data)
            except:
                continue
        q = 0
df_aggregate_user = pd.DataFrame(aggregate_user_data)

In [19]:
path = r"E:\Guvi\Final Projects\Phonepe Pulse Data\data\map\user\hover\country\india\state"
data = os.listdir(path)
map_users_data = []
q = 0

for i in data:
    path = fr"E:\Guvi\Final Projects\Phonepe Pulse Data\data\map\user\hover\country\india\state\{i}"
    data = os.listdir(path)
    for j in data:
        path = fr"E:\Guvi\Final Projects\Phonepe Pulse Data\data\map\user\hover\country\india\state\{i}\{j}"
        data = os.listdir(path)
        for k in data:
            q = q+1
            path1 = fr"E:\Guvi\Final Projects\Phonepe Pulse Data\data\map\user\hover\country\india\state\{i}\{j}\{k}"
            file = open(path1,'r')
            data = json.loads(file.read())
            #print(data)
            for l in data['data']['hoverData'].items():
                #print(l)
                registered_users = l[1]['registeredUsers']
                user_data = {
                        'State': i,
                        'Year': j,
                        'Quarter': q,
                        'District': l[0],
                        'Registered_Users': registered_users
                    }
                map_users_data.append(user_data)
        q = 0                   

path = r"E:\Guvi\Final Projects\Phonepe Pulse Data\data\top\transaction\country\india\state"
data = os.listdir(path)
top_transaction_data = []


for i in data:
    path = fr"E:\Guvi\Final Projects\Phonepe Pulse Data\data\top\transaction\country\india\state\{i}"
    state = i
    
    data1 = os.listdir(path)
    for j in data1:
        path = fr'E:\Guvi\Final Projects\Phonepe Pulse Data\data\top\transaction\country\india\state\{i}\{j}'
        data2 = os.listdir(path)
        q = 0
        for k in data2:
            q = q+1
            path = fr'E:\Guvi\Final Projects\Phonepe Pulse Data\data\top\transaction\country\india\state\{i}\{j}\{k}'
            #print(k)
            file = open(path,'r')
            data3 = json.loads(file.read())
            #print(data3)
            
            for t in range(len(data3['data']['districts'])):
                transaction_data = {
                            'State' : i,
                            'Year' : j,
                            'Quarter' : q,
                            'District' : data3['data']['districts'][t]['entityName'],
                            'Count' : data3['data']['districts'][t]['metric']['count'],
                            'Amount' : data3['data']['districts'][t]['metric']['amount']
                            }
                top_transaction_data.append(transaction_data)

df_top_transaction = pd.DataFrame(top_transaction_data)
df_top_transaction.State = df_top_transaction.State.str.title()
df_top_transaction['State'] = df_top_transaction['State'].str.replace(r'-', ' ', regex=True)
df_top_transaction['State'] = df_top_transaction['State'].str.replace(r'Islands', '', regex=True)
df_top_transaction['State'] = df_top_transaction['State'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu',regex=True)
top_transaction_data = df_top_transaction.T.to_dict().values()

In [21]:
mycon = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345"
)
mycursor = mycon.cursor()
mycursor.execute('create database if not exists phonepe_pulse')

mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345",
    database="phonepe_pulse"
)
mycursor = mydb.cursor()
query1 = "create table if not exists aggregate_transaction (State varchar(100), Year int, Quarter int, Transaction_Name varchar(100),	Count int,	Amount bigint)"
mycursor.execute(query1)
query2 = 'insert into aggregate_transaction (State,Year,Quarter,Transaction_Name,Count,Amount) values (%s,%s,%s,%s,%s,%s)'
for i in aggregate_transaction_data:
    value = tuple(i.values())
    #print(value)
    mycursor.execute(query2,value)
    mydb.commit()

query3 = "create table if not exists aggregate_users (State	varchar(50), Year int,	Quarter int, Registered_Users int,	Device_Brand varchar(50),	Device_Count int, Percentage_by_device float)"
mycursor.execute(query3)
query4 = 'insert into aggregate_users (State,Year,Quarter,Registered_Users,Device_Brand,Device_Count,Percentage_by_device) values (%s,%s,%s,%s,%s,%s,%s)'
for i in aggregate_user_data:
    value = tuple(i.values())
    #print(value)
    mycursor.execute(query4,value)
    mydb.commit()

query5 = "create table if not exists map_users (State varchar(50), Year int, Quarter int, District varchar(50), Registered_Users int)"
mycursor.execute(query5)
query6 = 'insert into map_users (State,Year,Quarter,District,Registered_Users) values (%s,%s,%s,%s,%s)'
for i in map_users_data:
    value = tuple(i.values())
    #print(value)
    mycursor.execute(query6,value)
    mydb.commit()

query7 = "create table if not exists top_transactions (State varchar(50), Year int, Quarter int, District varchar(50), Count int, Amount bigint)"
mycursor.execute(query7)
query8 = 'insert into top_transactions (State,Year,Quarter,District,Count,Amount) values (%s,%s,%s,%s,%s,%s)'
for i in top_transaction_data:
    value = tuple(i.values())
    #print(value)
    mycursor.execute(query8,value)
    mydb.commit()